- name: enable repos
  template:
    src: repos_template.j2 
    dest: /etc/yum.repos.d/open_ans-tower-lab.repo
    mode: '0644'
 
- name: install base tools and packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - httpie
    - python-pip